[package]
name = "bake"
version = "0.1.0"
authors = ["Michael Sproul <michael.sproul@data61.csiro.au>"]
edition = "2018"

[dependencies]
petgraph = "0.4"
tera = "0.11"
structopt = "0.2"
log = "0.4.6"
env_logger = "0.6.1"
